name: Publish Package to npmjs
on:
  release:
    types: [created, updated]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '12.22.x'
      - run: |
          cd bpmn-viewer 
          npm ci
          npm run all
          cp -f ./public/app.js ../assets/js/app.js
          cp -f ./public/app.css ../assets/css/app.css
          cp -rf ./public/vendor/bpmn-j* ../assets/css
          cd ..
          zip -r itop-bpmn-viewer.zip assets *itop-bpmnviewer.php extension.xml README.md
      
      - name: Add to release
        uses: softprops/action-gh-release@v1
        with:
          files: itop-bpmn-viewer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        